all:
  vars:
    ansible_user: gen
    ansible_python_interpreter: /run/current-system/sw/bin/python3

  children:
    workstations:
      hosts:
        glw:
          ansible_host: glw.lan
        batpc:
          ansible_host: batpc.lan
          ansible_user: bat

    homelab:
      hosts:
        homebase:
          ansible_host: homebase.freyground.com
