---
- name: Show NixOS flake metadata
  ansible.builtin.command:
    cmd: nix flake metadata
    chdir: "{{ nixos_config_dir }}"
  delegate_to: localhost
  run_once: true
  changed_when: false
  register: flake_meta

- name: Print flake metadata
  ansible.builtin.debug:
    msg: "{{ flake_meta.stdout_lines }}"
  delegate_to: localhost
  run_once: true

- name: Generate hardware configuration on host
  ansible.builtin.command: nixos-generate-config --show-hardware-config
  register: hwconfig
  changed_when: false
  become: true

- name: Save hardware configuration locally
  ansible.builtin.copy:
    content: "{{ hwconfig.stdout }}\n"
    dest: "{{ nixos_config_dir }}/pkg/hwconfig/{{ inventory_hostname }}.nix"
  delegate_to: localhost

- name: Stage hardware configuration in git
  ansible.builtin.command:
    cmd: git add pkg/hwconfig/{{ inventory_hostname }}.nix
    chdir: "{{ nixos_config_dir }}"
  delegate_to: localhost
  changed_when: true

- name: Update all flake locks
  ansible.builtin.command:
    cmd: make update-locks
    chdir: "{{ nixos_config_dir }}"
  delegate_to: localhost
  run_once: true

- name: Format nix files
  ansible.builtin.command:
    cmd: nix fmt .
    chdir: "{{ nixos_config_dir }}"
  delegate_to: localhost
  run_once: true

- name: Deploy NixOS configuration via colmena
  ansible.builtin.command:
    cmd: >
      env NIXPKGS_ALLOW_UNFREE=1
      nix run .#colmena -- apply --on {{ inventory_hostname }} {{ colmena_flags }}
    chdir: "{{ nixos_config_dir }}"
  delegate_to: localhost
